# Site settings
title: CookBoy Blog
SEOTitle: 煮食男孩的博客
header-img: img/post-bg-desk.jpg
email: liujr0206@outlook.com
description: "超人爆底裤"
keyword: "Blog, CookBoy, study, DS, Python"
url: "http://rong0206.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Rong0206/Rong0206.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "蛰伏,Cook是动词。"
sidebar-avatar: /img/portrait.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:
zhihu_username:     liujr27
github_username:    Rong0206
#facebook_username:
#jianshu_username:
#twitter_username:




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# Deprecation: The 'gems' configuration option has been renamed to 'plugins'.
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: liujr

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 98a1f28bbd496f56703b                            #生成的clientID
  clientSecret: 944f95d6106b8c7678a3d5aef3535c1a63c61eea    #生成的clientSecret
  repo: rong0206.github.io    #仓库名称
  owner: rong0206    #github用户名
  admin: rong0206
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-139606452-1'            # Format: UA-xxxxxx-xx
ga_domain:   auto                        # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends

#friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    }
#]
